import React, { Component } from 'react'
   
class About extends Component {
    constructor(props) {
        super(props);
        this.state = {  };
    }
    render() {
        return (
            <div>
                <div>Image</div>
                <div>
                    <h1>A HUMAN RIGHTS FRAME FOR AI RISKS AND HARMS</h1>
                    
                    <p>This website reframes a number of well-publicized controversies generated by AI
                    systems. By taking up a human rights lens, we can see how these classes of risks
                    and harms fall within the purview of human rights. We will focus on rights found in the
                    UDHR and the most significant human rights treaties: The International Covenant on
                    Civil and Political Rights (ICCPR) and the International Covenant on Economic, Social and Cultural Rights (ICESRC), which have been ratified by roughly 170 countries.
                    Together, these three documents make up the International Bill of Rights, which illustrates that human rights are “indivisible, interdependent, and interrelated.”19</p>
                </div>

            </div>
            
        );
    }
}

export default About;